name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c635d3d784d8d03fcf62cf17c53de60b5ff59724898617beb1c14c305f0f98c5"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.18"
