name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "028bc9aa4c04c2a74d009846639390fb057edddddec233c2d3280fdb3e83d111"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.18"
