name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b2e3100be538616ea0771d9a334c33ff19d76cc253920675b838164ab0d9b3d"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.18"
