name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2b960d89dafceeff139a4571d1ddea02c3cf055f91267550ede4f42c8d19915"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.18"
