name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4685191249075152c4febd0051cddb6e796e92c28645dabe555af3ae8750619"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"

[options]
datapack-folder = "datapacks"
