name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "309d65bf8b5dd517c10d2a64a54f32b43b8066e93eff4fd43acd72859abfc9d1"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.18"
