name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "933d98b5f1d59fc465acc85e88b95b292d9a4d64eae73136a8832aa007769cb3"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"
