name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e244af5e8a7b16d5050ef9ea45733b7b5ffe0d124b5534e1ae4b9f5d065abe4a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"

[options]
datapack-folder = "datapacks"
