name = "Dragoncraft"
author = "DragonMaus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "192ad220fbf18cd9d2e326f26bbfaa7e31586ed7d8d12e2c1b23bf12e59852b9"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0"

[options]
datapack-folder = "datapacks"
